### ISSUE TITLE
i have installed this in custom nodes but one node is still missing while loading the provided work flow, its the node which connects with reference_cond

### ISSUE THREAD

**Issue by Manish-cel** [ExponentialML/ComfyUI_VisualStylePrompting#24] opened 2024-04-01 18:39 UTC

**Comment by Manish-cel** [comment] 2024-04-01 18:42
![Uploading missing.png…]()

**Comment by acegraphx** [comment] 2024-04-02 08:03
same here
![image](https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/assets/807445/a8345c0f-fe9f-4cc0-950f-412e34e63601)

**Comment by pamparamm** [comment] 2024-04-02 14:40
Duplicate of #23.
> Example workflow is old and isn't working with the current version, will be fixed in https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/pull/18. Please refer to https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/issues/17 to get updated workflow

**Closed** 2024-04-08 06:13 UTC
